/* config-boingus.h. Generated by cmake from config-boingus.h.cmake */

/*
 * SPDX-FileCopyrightText: 2014 Hugo Pereira Da Costa <hugo.pereira@free.fr>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef config_boingus_h
#define config_boingus_h

/* Define to 1 if XCB libraries are found */
#cmakedefine01 BOINGUS_HAVE_X11

#endif
