/* config-boingus.h. Generated by cmake from config-boingus.h.cmake */

/*
 * SPDX-FileCopyrightText: 2014 Hugo Pereira Da Costa <hugo.pereira@free.fr>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef config_boingus_h
#define config_boingus_h

/* Define to 1 if QtQuick is available */
#cmakedefine01 BOINGUS_HAVE_QTQUICK

/* Define to 1 if QtX11Extras is available */
#cmakedefine01 BOINGUS_HAVE_QTX11EXTRAS

/* Define to 1 if FrameworkIntegration/Kstyle libraries are found */
#cmakedefine01 BOINGUS_HAVE_KSTYLE

#endif
